session_name: dev-${USER}
start_directory: "~"
windows:
  - window_name: watch
    options:
      automatic-rename: true
    layout: tiled
    panes:
      - shell_command:
          - htop
        start_directory: /var/log
      - shell_command:
          - cd /var/log
          - ls -al | grep \.log
      - echo hello
      -  # blank pane
  - window_name: editor
    options:
      automatic-rename: true
    focus: true
    layout: main-horizontal
    panes:
      - focus: true
        shell_command:
          - echo ok
