session_name: dev
start_directory: "~/src"
environment:
  NODE_ENV: development
windows:
  - window_name: watch
    focus: true
    options:
      automatic-rename: true
    layout: main-vertical
    panes:
      - focus: true
