session_name: dev
start_directory: "~"
windows:
  - window_name: watch
    options:
      automatic-rename: true
    layout: tiled
    panes:
      - shell_command:
          - echo
      - shell_command:
          - ls
  - window_name: editor
    options:
      automatic-rename: true
    focus: true
    layout: main-horizontal
    panes:
      - focus: true
